rules: 
  hk1:
    port: "47801"
    targets:
    - host: hk01.bg.gfw.plus
      port: 10010
    type: mix_tunnel_server_tcp+udp
  hk2:
    port: "47802"
    targets:
    - host: hk02.bg.gfw.plus
      port: 10010
    type: mix_tunnel_server_tcp+udp
  hk4:
    port: "47804"
    targets:
    - host: hk04.bg.gfw.plus
      port: 10010
    type: mix_tunnel_server_tcp+udp
  hk5:
    port: "47805"
    targets:
    - host: hk05.bg.gfw.plus
      port: 10010
    type: mix_tunnel_server_tcp+udp
  hk6:
    port: "47806"
    targets:
    - host: hk06.bg.gfw.plus
      port: 10010
    type: mix_tunnel_server_tcp+udp
  jp1:
    port: "47811"
    targets:
    - host: jp01.bg.gfw.plus
      port: 10010
    type: mix_tunnel_server_tcp+udp
  jp2:
    port: "47812"
    targets:
    - host: jp02.bg.gfw.plus
      port: 10010
    type: mix_tunnel_server_tcp+udp
  jp3:
    port: "47813"
    targets:
    - host: jp03.bg.gfw.plus
      port: 10010
    type: mix_tunnel_server_tcp+udp
  sg01:
    port: "47821"
    targets:
    - host: sg01.bg.gfw.plus
      port: 10010
    type: mix_tunnel_server_tcp+udp
  sg03:
    port: "47823"
    targets:
    - host: sg03.bg.gfw.plus
      port: 10010
    type: mix_tunnel_server_tcp+udp
  sg04:
    port: "47824"
    targets:
    - host: sg04.bg.gfw.plus
      port: 10010
    type: mix_tunnel_server_tcp+udp
cfips: []
